<?php

namespace Tests\Feature\misPruebas;

use App\Models\Rol;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CrearCategoriasTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        // Creamos el rol superadmin
        $rol = Rol::factory()->create(['nombre' => 'superadmin']);
        // Creamos un usuario
        $user = User::factory()->create();
        // Le asignamos el rol de superadmin para poder acceder al backend
        $user->roles()->sync($rol);

        // Actuamos como este usuario
        $this->actingAs($user);

    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_se_puede_acceder_a_la_pagina_de_alta_de_categorias()
    {
        // Ir a la página de crear etiquetas
        $response = $this->get('/admin/categorias/crear');

        // Comprobar que accede a la página
        $response->assertStatus(200);
    }

    public function test_se_puede_crear_una_categoria ()
    {
        $this->withoutExceptionHandling();
        $response = $this->post('/admin/categorias', [
            'nombre' => 'test'
        ]);

        $response->assertRedirect('/admin/categorias');
    }
}
